import type { NextPage } from 'next'
import Head from 'next/head'
import Inicio from '../../comp../../components/Inicio'
import Navbar from '../../components/Navbar'
import Sidebar from '../../components/Sidebar'
import styles from './styles.module.scss'
 
const Dashboard: NextPage = () => {

  return (
      <>
         <Head>
             <title>Dashboard</title>
             <meta name='description' content='Generated by create next app' />
             <link rel='icon' href='/favicon.ico' />
         </Head>
 
         <main className='main mainDashboard'>
            <Navbar />
            <div className="contentDashboard">
              <Sidebar />
              <Inicio />
            </div>
         </main>
      </>
    )
}


export default Dashboard