import type { NextPage } from 'next'
import Head from 'next/head'
import HistoricComponent from '../../components/Historic'
import Navbar from '../../components/Navbar'
import Sidebar from '../../components/Sidebar'
import styles from './styles.module.scss'
 
const Historic: NextPage = () => {
  return (
      <>
         <Head>
             <title>Histórico</title>
             <meta name='description' content='Generated by create next app' />
             <link rel='icon' href='/favicon.ico' />
         </Head>
 
         <main className='main mainDashboard'>
            <Navbar />
            <div className="contentDashboard">
              <Sidebar />
              <HistoricComponent />
            </div>
         </main>
      </>
    )
}


export default Historic