import 'primereact/resources/themes/lara-light-indigo/theme.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.css';
import '@/styles/app.scss'
import { Inter, Kumbh_Sans } from 'next/font/google'
import { api } from '@/utils';
import { cookies } from 'next/dist/client/components/headers';

const kumbh = Kumbh_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  const cookie = cookies()
  const token = cookie.get('nextAuth.token')?.value
  const refreshToken = cookie.get('nextAuth.refresh')?.value
  const expireToken = cookie.get('nextAuth.expire_token')?.value
  const userEmail = cookie.get('nextAuth.email')?.value
  api.defaults.headers['Authorization'] = `Bearer ${token}`
  const installations = api.get('/user/installations').then(res => { console.log(res.data.installations.results) }).catch(err => { console.log(err); return [] })
  return (
    <html lang="en">
      <body className={kumbh.className}>{children}</body>
    </html>
  )
}
