
import Navbar from "@/components/Navbar"
import Sidebar from "@/components/Sidebar"
import { api } from "@/utils"
import { cookies } from "next/dist/client/components/headers"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function AdminLayout({ children, params }: { children: React.ReactNode, params:{installations:string} }) {
  const cookie = cookies()
  const token = cookie.get('nextAuth.token')?.value
  const refreshToken = cookie.get('nextAuth.refresh')?.value
  const expireToken = cookie.get('nextAuth.expire_token')?.value
  const userEmail = cookie.get('nextAuth.email')?.value

  api.defaults.headers['Authorization'] = `Bearer ${token}`
  async function userGroups(token:string) {
    const jwtData = token.split('.')[1];
    const decodedJwtData = atob(jwtData);
    const jwtPayload = JSON.parse(decodedJwtData);
  
    if (jwtPayload['cognito:groups']) {
      return jwtPayload;
    }
  
    return [];
  }

  const user = await api.get('/user/profile').then(res => { return res.data }).catch(err => { console.log(err); return [] })
  const installations = await api.get('/user/installations').then(res => { return res.data.installations.results }).catch(err => { console.log(err); return [] })
  

  return (
    <main className="main mainDashboard">
      <Navbar token={token} userData={user} installationsData={installations}/>
      <div className="contentDashboard">
        <Sidebar/>
        {children}
      </div>
    </main>
  )
}